#####################################################
#                    Data upload                    #
#####################################################
# This code is to upload the data related to the number of fibres generated by ImageJ
# The .csv file to upload will need to have the following columns:
# Slice; Count;
# "Count" correspond to the fibre counted by imageJ

# "Slice" correspond to the name of the receiver swatch and must be written in this form "W000_G1_G3_8_perp_B.TIF" for the wash experiments
# with Wxxx the wash number, Gx the garment number, "_x_" the contact area number and "_B" the condition of the experimentr
# condition experiments: "B" for Before transfer, "Atr" for after transfer

#####################################################
#             1 GARMENT - NO DERTERGENT             #
#####################################################
#-----------------------------------------------------------#
#                         W000_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G1 <- read.csv('./Fibre count Summary/W000_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G1B <- W000_G1 %>% filter(grepl('_B.', Slice))
W000_G1Atr <- W000_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G1B and W000_G1Atr
W000_G1B$Slice<- gsub(".TIF","",W000_G1B$Slice)
W000_G1Atr$Slice<- gsub(".TIF","",W000_G1Atr$Slice)

# Create table
W000_G1_Dataset_pending <- data.frame(rbind(W000_G1B$Slice, W000_G1B$Count, W000_G1Atr$Count))
W000_G1_Dataset<-as.data.frame(t(W000_G1_Dataset_pending))
names(W000_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G1_Dataset[,2:3] = apply(W000_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G1,W000_G1B,W000_G1Atr,W000_G1_Dataset_pending)

#-----------------------------------------------------------#
#                         W001_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001_G1 <- read.csv('./Fibre count Summary/W001_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001_G1B <- W001_G1 %>% filter(grepl('_B.', Slice))
W001_G1Atr <- W001_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001_G1B and W001_G1Atr
W001_G1B$Slice<- gsub(".TIF","",W001_G1B$Slice)
W001_G1Atr$Slice<- gsub(".TIF","",W001_G1Atr$Slice)

# Create table
W001_G1_Dataset_pending <- data.frame(rbind(W001_G1B$Slice, W001_G1B$Count, W001_G1Atr$Count))
W001_G1_Dataset<-as.data.frame(t(W001_G1_Dataset_pending))
names(W001_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G1_Dataset[,2:3] = apply(W001_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001_G1,W001_G1B,W001_G1Atr,W001_G1_Dataset_pending)

#-----------------------------------------------------------#
#                         W002_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002_G1 <- read.csv('./Fibre count Summary/W002_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002_G1B <- W002_G1 %>% filter(grepl('_B.', Slice))
W002_G1Atr <- W002_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002_G1B and W002_G1Atr
W002_G1B$Slice<- gsub(".TIF","",W002_G1B$Slice)
W002_G1Atr$Slice<- gsub(".TIF","",W002_G1Atr$Slice)

# Create table
W002_G1_Dataset_pending <- data.frame(rbind(W002_G1B$Slice, W002_G1B$Count, W002_G1Atr$Count))
W002_G1_Dataset<-as.data.frame(t(W002_G1_Dataset_pending))
names(W002_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G1_Dataset[,2:3] = apply(W002_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002_G1,W002_G1B,W002_G1Atr,W002_G1_Dataset_pending)

#-----------------------------------------------------------#
#                         W003_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003_G1 <- read.csv('./Fibre count Summary/W003_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003_G1B <- W003_G1 %>% filter(grepl('_B.', Slice))
W003_G1Atr <- W003_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003_G1B and W003_G1Atr
W003_G1B$Slice<- gsub(".TIF","",W003_G1B$Slice)
W003_G1Atr$Slice<- gsub(".TIF","",W003_G1Atr$Slice)

# Create table
W003_G1_Dataset_pending <- data.frame(rbind(W003_G1B$Slice, W003_G1B$Count, W003_G1Atr$Count))
W003_G1_Dataset<-as.data.frame(t(W003_G1_Dataset_pending))
names(W003_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G1_Dataset[,2:3] = apply(W003_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003_G1,W003_G1B,W003_G1Atr,W003_G1_Dataset_pending)

#-----------------------------------------------------------#
#                         W004_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004_G1 <- read.csv('./Fibre count Summary/W004_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004_G1B <- W004_G1 %>% filter(grepl('_B.', Slice))
W004_G1Atr <- W004_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004_G1B and W004_G1Atr
W004_G1B$Slice<- gsub(".TIF","",W004_G1B$Slice)
W004_G1Atr$Slice<- gsub(".TIF","",W004_G1Atr$Slice)

# Create table
W004_G1_Dataset_pending <- data.frame(rbind(W004_G1B$Slice, W004_G1B$Count, W004_G1Atr$Count))
W004_G1_Dataset<-as.data.frame(t(W004_G1_Dataset_pending))
names(W004_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G1_Dataset[,2:3] = apply(W004_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004_G1,W004_G1B,W004_G1Atr,W004_G1_Dataset_pending)

#-----------------------------------------------------------#
#                         W005_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005_G1 <- read.csv('./Fibre count Summary/W005_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005_G1B <- W005_G1 %>% filter(grepl('_B.', Slice))
W005_G1Atr <- W005_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005_G1B and W005_G1Atr
W005_G1B$Slice<- gsub(".TIF","",W005_G1B$Slice)
W005_G1Atr$Slice<- gsub(".TIF","",W005_G1Atr$Slice)

# Create table
W005_G1_Dataset_pending <- data.frame(rbind(W005_G1B$Slice, W005_G1B$Count, W005_G1Atr$Count))
W005_G1_Dataset<-as.data.frame(t(W005_G1_Dataset_pending))
names(W005_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G1_Dataset[,2:3] = apply(W005_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005_G1,W005_G1B,W005_G1Atr,W005_G1_Dataset_pending)

#-----------------------------------------------------------#
#                         W006_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006_G1 <- read.csv('./Fibre count Summary/W006_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W006_G1B <- W006_G1 %>% filter(grepl('_B.', Slice))
W006_G1Atr <- W006_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W006_G1B and W006_G1Atr
W006_G1B$Slice<- gsub(".TIF","",W006_G1B$Slice)
W006_G1Atr$Slice<- gsub(".TIF","",W006_G1Atr$Slice)

# Create table
W006_G1_Dataset_pending <- data.frame(rbind(W006_G1B$Slice, W006_G1B$Count, W006_G1Atr$Count))
W006_G1_Dataset<-as.data.frame(t(W006_G1_Dataset_pending))
names(W006_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G1_Dataset[,2:3] = apply(W006_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006_G1,W006_G1B,W006_G1Atr,W006_G1_Dataset_pending)

#-----------------------------------------------------------#
#                         W007_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W007_G1 <- read.csv('./Fibre count Summary/W007_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W007_G1B <- W007_G1 %>% filter(grepl('_B.', Slice))
W007_G1Atr <- W007_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W007_G1B and W007_G1Atr
W007_G1B$Slice<- gsub(".TIF","",W007_G1B$Slice)
W007_G1Atr$Slice<- gsub(".TIF","",W007_G1Atr$Slice)

# Create table
W007_G1_Dataset_pending <- data.frame(rbind(W007_G1B$Slice, W007_G1B$Count, W007_G1Atr$Count))
W007_G1_Dataset<-as.data.frame(t(W007_G1_Dataset_pending))
names(W007_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W007_G1_Dataset[,2:3] = apply(W007_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W007_G1,W007_G1B,W007_G1Atr,W007_G1_Dataset_pending)

#-----------------------------------------------------------#
#                         W009_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W009_G1 <- read.csv('./Fibre count Summary/W009_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W009_G1B <- W009_G1 %>% filter(grepl('_B.', Slice))
W009_G1Atr <- W009_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W009_G1B and W009_G1Atr
W009_G1B$Slice<- gsub(".TIF","",W009_G1B$Slice)
W009_G1Atr$Slice<- gsub(".TIF","",W009_G1Atr$Slice)

# Create table
W009_G1_Dataset_pending <- data.frame(rbind(W009_G1B$Slice, W009_G1B$Count, W009_G1Atr$Count))
W009_G1_Dataset<-as.data.frame(t(W009_G1_Dataset_pending))
names(W009_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W009_G1_Dataset[,2:3] = apply(W009_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W009_G1,W009_G1B,W009_G1Atr,W009_G1_Dataset_pending)

#-----------------------------------------------------------#
#                         W011_G1                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W011_G1 <- read.csv('./Fibre count Summary/W011_G1_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W011_G1B <- W011_G1 %>% filter(grepl('_B.', Slice))
W011_G1Atr <- W011_G1 %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W011_G1B and W011_G1Atr
W011_G1B$Slice<- gsub(".TIF","",W011_G1B$Slice)
W011_G1Atr$Slice<- gsub(".TIF","",W011_G1Atr$Slice)

# Create table
W011_G1_Dataset_pending <- data.frame(rbind(W011_G1B$Slice, W011_G1B$Count, W011_G1Atr$Count))
W011_G1_Dataset<-as.data.frame(t(W011_G1_Dataset_pending))
names(W011_G1_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W011_G1_Dataset[,2:3] = apply(W011_G1_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W011_G1,W011_G1B,W011_G1Atr,W011_G1_Dataset_pending)

#####################################################
#             5 GARMENTS - NO DETERGENT             #
#####################################################
#-----------------------------------------------------------#
#                             W000                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000B <- read.csv('./Fibre count Summary/W000_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W000Atr <- read.csv('./Fibre count Summary/W000_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W000B$Slice<- gsub("_B.TIF","",W000B$Slice)

# Create table
W000_G5_Dataset_pending <- data.frame(rbind(W000B$Slice, W000B$Count, W000Atr$Count))
W000_G5_Dataset<-as.data.frame(t(W000_G5_Dataset_pending))
names(W000_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G5_Dataset[,2:3] = apply(W000_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000B,W000Atr,W000_G5_Dataset_pending)

#-----------------------------------------------------------#
#                              W001                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001B <- read.csv('./Fibre count Summary/W001_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W001Atr <- read.csv('./Fibre count Summary/W001_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W001B$Slice<- gsub("_B.TIF","",W001B$Slice)

# Create table
W001_G5_Dataset_pending <- data.frame(rbind(W001B$Slice, W001B$Count, W001Atr$Count))
W001_G5_Dataset<-as.data.frame(t(W001_G5_Dataset_pending))
names(W001_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G5_Dataset[,2:3] = apply(W001_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001B,W001Atr,W001_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W002                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002B <- read.csv('./Fibre count Summary/W002_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W002Atr <- read.csv('./Fibre count Summary/W002_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W002B$Slice<- gsub("_B.TIF","",W002B$Slice)

# Create table
W002_G5_Dataset_pending <- data.frame(rbind(W002B$Slice, W002B$Count, W002Atr$Count))
W002_G5_Dataset<-as.data.frame(t(W002_G5_Dataset_pending))
names(W002_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G5_Dataset[,2:3] = apply(W002_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002B,W002Atr,W002_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W003                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003B <- read.csv('./Fibre count Summary/W003_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W003Atr <- read.csv('./Fibre count Summary/W003_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W003B$Slice<- gsub("_B.TIF","",W003B$Slice)

# Create table
W003_G5_Dataset_pending <- data.frame(rbind(W003B$Slice, W003B$Count, W003Atr$Count))
W003_G5_Dataset<-as.data.frame(t(W003_G5_Dataset_pending))
names(W003_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G5_Dataset[,2:3] = apply(W003_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003B,W003Atr,W003_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W004                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004B <- read.csv('./Fibre count Summary/W004_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W004Atr <- read.csv('./Fibre count Summary/W004_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W004B$Slice<- gsub("_B.TIF","",W004B$Slice)

# Create table
W004_G5_Dataset_pending <- data.frame(rbind(W004B$Slice, W004B$Count, W004Atr$Count))
W004_G5_Dataset<-as.data.frame(t(W004_G5_Dataset_pending))
names(W004_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G5_Dataset[,2:3] = apply(W004_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004B,W004Atr,W004_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W005                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005B <- read.csv('./Fibre count Summary/W005_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W005Atr <- read.csv('./Fibre count Summary/W005_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W005B$Slice<- gsub("_B.TIF","",W005B$Slice)

# Create table
W005_G5_Dataset_pending <- data.frame(rbind(W005B$Slice, W005B$Count, W005Atr$Count))
W005_G5_Dataset<-as.data.frame(t(W005_G5_Dataset_pending))
names(W005_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G5_Dataset[,2:3] = apply(W005_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005B,W005Atr,W005_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W006                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006B <- read.csv('./Fibre count Summary/W006_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W006Atr <- read.csv('./Fibre count Summary/W006_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W006B$Slice<- gsub("_B.TIF","",W006B$Slice)

# Create table
W006_G5_Dataset_pending <- data.frame(rbind(W006B$Slice, W006B$Count, W006Atr$Count))
W006_G5_Dataset<-as.data.frame(t(W006_G5_Dataset_pending))
names(W006_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G5_Dataset[,2:3] = apply(W006_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006B,W006Atr,W006_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W007                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W007B <- read.csv('./Fibre count Summary/W007_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W007Atr <- read.csv('./Fibre count Summary/W007_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W007B$Slice<- gsub("_B.TIF","",W007B$Slice)

# Create table
W007_G5_Dataset_pending <- data.frame(rbind(W007B$Slice, W007B$Count, W007Atr$Count))
W007_G5_Dataset<-as.data.frame(t(W007_G5_Dataset_pending))
names(W007_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W007_G5_Dataset[,2:3] = apply(W007_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W007B,W007Atr,W007_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W008                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W008B <- read.csv('./Fibre count Summary/W008_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W008Atr <- read.csv('./Fibre count Summary/W008_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W008B$Slice<- gsub("_B.TIF","",W008B$Slice)

# Create table
W008_G5_Dataset_pending <- data.frame(rbind(W008B$Slice, W008B$Count, W008Atr$Count))
W008_G5_Dataset<-as.data.frame(t(W008_G5_Dataset_pending))
names(W008_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W008_G5_Dataset[,2:3] = apply(W008_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W008B,W008Atr,W008_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W009                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W009B <- read.csv('./Fibre count Summary/W009_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W009Atr <- read.csv('./Fibre count Summary/W009_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W009B$Slice<- gsub("_B.TIF","",W009B$Slice)

# Create table
W009_G5_Dataset_pending <- data.frame(rbind(W009B$Slice, W009B$Count, W009Atr$Count))
W009_G5_Dataset<-as.data.frame(t(W009_G5_Dataset_pending))
names(W009_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W009_G5_Dataset[,2:3] = apply(W009_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W009B,W009Atr,W009_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W010                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W010B <- read.csv('./Fibre count Summary/W010_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W010Atr <- read.csv('./Fibre count Summary/W010_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W010B$Slice<- gsub("_B.TIF","",W010B$Slice)

# Create table
W010_G5_Dataset_pending <- data.frame(rbind(W010B$Slice, W010B$Count, W010Atr$Count))
W010_G5_Dataset<-as.data.frame(t(W010_G5_Dataset_pending))
names(W010_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W010_G5_Dataset[,2:3] = apply(W010_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W010B,W010Atr,W010_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W011                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W011B <- read.csv('./Fibre count Summary/W011_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W011Atr <- read.csv('./Fibre count Summary/W011_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W011B$Slice<- gsub("_B.TIF","",W011B$Slice)

# Create table
W011_G5_Dataset_pending <- data.frame(rbind(W011B$Slice, W011B$Count, W011Atr$Count))
W011_G5_Dataset<-as.data.frame(t(W011_G5_Dataset_pending))
names(W011_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W011_G5_Dataset[,2:3] = apply(W011_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W011B,W011Atr,W011_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W012                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W012B <- read.csv('./Fibre count Summary/W012_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W012Atr <- read.csv('./Fibre count Summary/W012_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W012B$Slice<- gsub("_B.TIF","",W012B$Slice)

# Create table
W012_G5_Dataset_pending <- data.frame(rbind(W012B$Slice, W012B$Count, W012Atr$Count))
W012_G5_Dataset<-as.data.frame(t(W012_G5_Dataset_pending))
names(W012_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W012_G5_Dataset[,2:3] = apply(W012_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W012B,W012Atr,W012_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W013                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W013B <- read.csv('./Fibre count Summary/W013_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W013Atr <- read.csv('./Fibre count Summary/W013_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W013B$Slice<- gsub("_B.TIF","",W013B$Slice)

# Create table
W013_G5_Dataset_pending <- data.frame(rbind(W013B$Slice, W013B$Count, W013Atr$Count))
W013_G5_Dataset<-as.data.frame(t(W013_G5_Dataset_pending))
names(W013_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W013_G5_Dataset[,2:3] = apply(W013_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W013B,W013Atr,W013_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W014                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W014B <- read.csv('./Fibre count Summary/W014_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W014Atr <- read.csv('./Fibre count Summary/W014_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W014B$Slice<- gsub("_B.TIF","",W014B$Slice)

# Create table
W014_G5_Dataset_pending <- data.frame(rbind(W014B$Slice, W014B$Count, W014Atr$Count))
W014_G5_Dataset<-as.data.frame(t(W014_G5_Dataset_pending))
names(W014_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W014_G5_Dataset[,2:3] = apply(W014_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W014B,W014Atr,W014_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W015                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W015B <- read.csv('./Fibre count Summary/W015_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W015Atr <- read.csv('./Fibre count Summary/W015_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W015B$Slice<- gsub("_B.TIF","",W015B$Slice)

# Create table
W015_G5_Dataset_pending <- data.frame(rbind(W015B$Slice, W015B$Count, W015Atr$Count))
W015_G5_Dataset<-as.data.frame(t(W015_G5_Dataset_pending))
names(W015_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W015_G5_Dataset[,2:3] = apply(W015_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W015B,W015Atr,W015_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W016                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W016B <- read.csv('./Fibre count Summary/W016_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W016Atr <- read.csv('./Fibre count Summary/W016_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W016B$Slice<- gsub("_B.TIF","",W016B$Slice)

# Create table
W016_G5_Dataset_pending <- data.frame(rbind(W016B$Slice, W016B$Count, W016Atr$Count))
W016_G5_Dataset<-as.data.frame(t(W016_G5_Dataset_pending))
names(W016_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W016_G5_Dataset[,2:3] = apply(W016_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W016B,W016Atr,W016_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W017                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W017B <- read.csv('./Fibre count Summary/W017_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W017Atr <- read.csv('./Fibre count Summary/W017_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W017B$Slice<- gsub("_B.TIF","",W017B$Slice)

# Create table
W017_G5_Dataset_pending <- data.frame(rbind(W017B$Slice, W017B$Count, W017Atr$Count))
W017_G5_Dataset<-as.data.frame(t(W017_G5_Dataset_pending))
names(W017_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W017_G5_Dataset[,2:3] = apply(W017_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W017B,W017Atr,W017_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W018                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W018B <- read.csv('./Fibre count Summary/W018_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W018Atr <- read.csv('./Fibre count Summary/W018_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W018B$Slice<- gsub("_B.TIF","",W018B$Slice)

# Create table
W018_G5_Dataset_pending <- data.frame(rbind(W018B$Slice, W018B$Count, W018Atr$Count))
W018_G5_Dataset<-as.data.frame(t(W018_G5_Dataset_pending))
names(W018_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W018_G5_Dataset[,2:3] = apply(W018_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W018B,W018Atr,W018_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W019                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W019B <- read.csv('./Fibre count Summary/W019_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W019Atr <- read.csv('./Fibre count Summary/W019_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W019B$Slice<- gsub("_B.TIF","",W019B$Slice)

# Create table
W019_G5_Dataset_pending <- data.frame(rbind(W019B$Slice, W019B$Count, W019Atr$Count))
W019_G5_Dataset<-as.data.frame(t(W019_G5_Dataset_pending))
names(W019_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W019_G5_Dataset[,2:3] = apply(W019_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W019B,W019Atr,W019_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W020                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W020B <- read.csv('./Fibre count Summary/W020_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W020Atr <- read.csv('./Fibre count Summary/W020_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W020B$Slice<- gsub("_B.TIF","",W020B$Slice)

# Create table
W020_G5_Dataset_pending <- data.frame(rbind(W020B$Slice, W020B$Count, W020Atr$Count))
W020_G5_Dataset<-as.data.frame(t(W020_G5_Dataset_pending))
names(W020_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W020_G5_Dataset[,2:3] = apply(W020_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W020B,W020Atr,W020_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W021                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W021B <- read.csv('./Fibre count Summary/W021_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W021Atr <- read.csv('./Fibre count Summary/W021_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W021B$Slice<- gsub("_B.TIF","",W021B$Slice)

# Create table
W021_G5_Dataset_pending <- data.frame(rbind(W021B$Slice, W021B$Count, W021Atr$Count))
W021_G5_Dataset<-as.data.frame(t(W021_G5_Dataset_pending))
names(W021_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W021_G5_Dataset[,2:3] = apply(W021_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W021B,W021Atr,W021_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W022                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W022B <- read.csv('./Fibre count Summary/W022_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W022Atr <- read.csv('./Fibre count Summary/W022_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W022B$Slice<- gsub("_B.TIF","",W022B$Slice)

# Create table
W022_G5_Dataset_pending <- data.frame(rbind(W022B$Slice, W022B$Count, W022Atr$Count))
W022_G5_Dataset<-as.data.frame(t(W022_G5_Dataset_pending))
names(W022_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W022_G5_Dataset[,2:3] = apply(W022_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W022B,W022Atr,W022_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W023                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W023B <- read.csv('./Fibre count Summary/W023_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W023Atr <- read.csv('./Fibre count Summary/W023_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W023B$Slice<- gsub("_B.TIF","",W023B$Slice)

# Create table
W023_G5_Dataset_pending <- data.frame(rbind(W023B$Slice, W023B$Count, W023Atr$Count))
W023_G5_Dataset<-as.data.frame(t(W023_G5_Dataset_pending))
names(W023_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W023_G5_Dataset[,2:3] = apply(W023_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W023B,W023Atr,W023_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W024                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W024B <- read.csv('./Fibre count Summary/W024_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W024Atr <- read.csv('./Fibre count Summary/W024_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W024B$Slice<- gsub("_B.TIF","",W024B$Slice)

# Create table
W024_G5_Dataset_pending <- data.frame(rbind(W024B$Slice, W024B$Count, W024Atr$Count))
W024_G5_Dataset<-as.data.frame(t(W024_G5_Dataset_pending))
names(W024_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W024_G5_Dataset[,2:3] = apply(W024_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W024B,W024Atr,W024_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W025                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W025B <- read.csv('./Fibre count Summary/W025_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W025Atr <- read.csv('./Fibre count Summary/W025_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W025B$Slice<- gsub("_B.TIF","",W025B$Slice)

# Create table
W025_G5_Dataset_pending <- data.frame(rbind(W025B$Slice, W025B$Count, W025Atr$Count))
W025_G5_Dataset<-as.data.frame(t(W025_G5_Dataset_pending))
names(W025_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W025_G5_Dataset[,2:3] = apply(W025_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W025B,W025Atr,W025_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W026                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W026B <- read.csv('./Fibre count Summary/W026_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W026Atr <- read.csv('./Fibre count Summary/W026_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W026B$Slice<- gsub("_B.TIF","",W026B$Slice)

# Create table
W026_G5_Dataset_pending <- data.frame(rbind(W026B$Slice, W026B$Count, W026Atr$Count))
W026_G5_Dataset<-as.data.frame(t(W026_G5_Dataset_pending))
names(W026_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W026_G5_Dataset[,2:3] = apply(W026_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W026B,W026Atr,W026_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W027                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W027B <- read.csv('./Fibre count Summary/W027_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W027Atr <- read.csv('./Fibre count Summary/W027_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W027B$Slice<- gsub("_B.TIF","",W027B$Slice)

# Create table
W027_G5_Dataset_pending <- data.frame(rbind(W027B$Slice, W027B$Count, W027Atr$Count))
W027_G5_Dataset<-as.data.frame(t(W027_G5_Dataset_pending))
names(W027_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W027_G5_Dataset[,2:3] = apply(W027_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W027B,W027Atr,W027_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W028                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W028B <- read.csv('./Fibre count Summary/W028_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W028Atr <- read.csv('./Fibre count Summary/W028_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W028B$Slice<- gsub("_B.TIF","",W028B$Slice)

# Create table
W028_G5_Dataset_pending <- data.frame(rbind(W028B$Slice, W028B$Count, W028Atr$Count))
W028_G5_Dataset<-as.data.frame(t(W028_G5_Dataset_pending))
names(W028_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W028_G5_Dataset[,2:3] = apply(W028_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W028B,W028Atr,W028_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W029                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W029B <- read.csv('./Fibre count Summary/W029_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W029Atr <- read.csv('./Fibre count Summary/W029_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W029B$Slice<- gsub("_B.TIF","",W029B$Slice)

# Create table
W029_G5_Dataset_pending <- data.frame(rbind(W029B$Slice, W029B$Count, W029Atr$Count))
W029_G5_Dataset<-as.data.frame(t(W029_G5_Dataset_pending))
names(W029_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W029_G5_Dataset[,2:3] = apply(W029_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W029B,W029Atr,W029_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W030                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W030B <- read.csv('./Fibre count Summary/W030_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W030Atr <- read.csv('./Fibre count Summary/W030_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W030B$Slice<- gsub("_B.TIF","",W030B$Slice)

# Create table
W030_G5_Dataset_pending <- data.frame(rbind(W030B$Slice, W030B$Count, W030Atr$Count))
W030_G5_Dataset<-as.data.frame(t(W030_G5_Dataset_pending))
names(W030_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W030_G5_Dataset[,2:3] = apply(W030_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W030B,W030Atr,W030_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W031                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W031B <- read.csv('./Fibre count Summary/W031_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W031Atr <- read.csv('./Fibre count Summary/W031_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W031B$Slice<- gsub("_B.TIF","",W031B$Slice)

# Create table
W031_G5_Dataset_pending <- data.frame(rbind(W031B$Slice, W031B$Count, W031Atr$Count))
W031_G5_Dataset<-as.data.frame(t(W031_G5_Dataset_pending))
names(W031_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W031_G5_Dataset[,2:3] = apply(W031_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W031B,W031Atr,W031_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W032                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W032B <- read.csv('./Fibre count Summary/W032_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W032Atr <- read.csv('./Fibre count Summary/W032_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W032B$Slice<- gsub("_B.TIF","",W032B$Slice)

# Create table
W032_G5_Dataset_pending <- data.frame(rbind(W032B$Slice, W032B$Count, W032Atr$Count))
W032_G5_Dataset<-as.data.frame(t(W032_G5_Dataset_pending))
names(W032_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W032_G5_Dataset[,2:3] = apply(W032_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W032B,W032Atr,W032_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W033                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W033B <- read.csv('./Fibre count Summary/W033_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W033Atr <- read.csv('./Fibre count Summary/W033_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W033B$Slice<- gsub("_B.TIF","",W033B$Slice)

# Create table
W033_G5_Dataset_pending <- data.frame(rbind(W033B$Slice, W033B$Count, W033Atr$Count))
W033_G5_Dataset<-as.data.frame(t(W033_G5_Dataset_pending))
names(W033_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W033_G5_Dataset[,2:3] = apply(W033_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W033B,W033Atr,W033_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W034                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W034B <- read.csv('./Fibre count Summary/W034_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W034Atr <- read.csv('./Fibre count Summary/W034_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W034B$Slice<- gsub("_B.TIF","",W034B$Slice)

# Create table
W034_G5_Dataset_pending <- data.frame(rbind(W034B$Slice, W034B$Count, W034Atr$Count))
W034_G5_Dataset<-as.data.frame(t(W034_G5_Dataset_pending))
names(W034_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W034_G5_Dataset[,2:3] = apply(W034_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W034B,W034Atr,W034_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W035                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W035B <- read.csv('./Fibre count Summary/W035_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W035Atr <- read.csv('./Fibre count Summary/W035_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W035B$Slice<- gsub("_B.TIF","",W035B$Slice)

# Create table
W035_G5_Dataset_pending <- data.frame(rbind(W035B$Slice, W035B$Count, W035Atr$Count))
W035_G5_Dataset<-as.data.frame(t(W035_G5_Dataset_pending))
names(W035_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W035_G5_Dataset[,2:3] = apply(W035_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W035B,W035Atr,W035_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W036                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W036B <- read.csv('./Fibre count Summary/W036_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W036Atr <- read.csv('./Fibre count Summary/W036_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W036B$Slice<- gsub("_B.TIF","",W036B$Slice)

# Create table
W036_G5_Dataset_pending <- data.frame(rbind(W036B$Slice, W036B$Count, W036Atr$Count))
W036_G5_Dataset<-as.data.frame(t(W036_G5_Dataset_pending))
names(W036_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W036_G5_Dataset[,2:3] = apply(W036_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W036B,W036Atr,W036_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W037                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W037B <- read.csv('./Fibre count Summary/W037_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W037Atr <- read.csv('./Fibre count Summary/W037_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W037B$Slice<- gsub("_B.TIF","",W037B$Slice)

# Create table
W037_G5_Dataset_pending <- data.frame(rbind(W037B$Slice, W037B$Count, W037Atr$Count))
W037_G5_Dataset<-as.data.frame(t(W037_G5_Dataset_pending))
names(W037_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W037_G5_Dataset[,2:3] = apply(W037_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W037B,W037Atr,W037_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W038                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W038B <- read.csv('./Fibre count Summary/W038_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W038Atr <- read.csv('./Fibre count Summary/W038_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W038B$Slice<- gsub("_B.TIF","",W038B$Slice)

# Create table
W038_G5_Dataset_pending <- data.frame(rbind(W038B$Slice, W038B$Count, W038Atr$Count))
W038_G5_Dataset<-as.data.frame(t(W038_G5_Dataset_pending))
names(W038_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W038_G5_Dataset[,2:3] = apply(W038_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W038B,W038Atr,W038_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W039                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W039B <- read.csv('./Fibre count Summary/W039_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W039Atr <- read.csv('./Fibre count Summary/W039_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W039B$Slice<- gsub("_B.TIF","",W039B$Slice)

# Create table
W039_G5_Dataset_pending <- data.frame(rbind(W039B$Slice, W039B$Count, W039Atr$Count))
W039_G5_Dataset<-as.data.frame(t(W039_G5_Dataset_pending))
names(W039_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W039_G5_Dataset[,2:3] = apply(W039_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W039B,W039Atr,W039_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W040                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W040B <- read.csv('./Fibre count Summary/W040_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W040Atr <- read.csv('./Fibre count Summary/W040_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W040B$Slice<- gsub("_B.TIF","",W040B$Slice)

# Create table
W040_G5_Dataset_pending <- data.frame(rbind(W040B$Slice, W040B$Count, W040Atr$Count))
W040_G5_Dataset<-as.data.frame(t(W040_G5_Dataset_pending))
names(W040_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W040_G5_Dataset[,2:3] = apply(W040_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W040B,W040Atr,W040_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W041                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W041B <- read.csv('./Fibre count Summary/W041_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W041Atr <- read.csv('./Fibre count Summary/W041_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W041B$Slice<- gsub("_B.TIF","",W041B$Slice)

# Create table
W041_G5_Dataset_pending <- data.frame(rbind(W041B$Slice, W041B$Count, W041Atr$Count))
W041_G5_Dataset<-as.data.frame(t(W041_G5_Dataset_pending))
names(W041_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W041_G5_Dataset[,2:3] = apply(W041_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W041B,W041Atr,W041_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W042                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W042B <- read.csv('./Fibre count Summary/W042_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W042Atr <- read.csv('./Fibre count Summary/W042_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W042B$Slice<- gsub("_B.TIF","",W042B$Slice)

# Create table
W042_G5_Dataset_pending <- data.frame(rbind(W042B$Slice, W042B$Count, W042Atr$Count))
W042_G5_Dataset<-as.data.frame(t(W042_G5_Dataset_pending))
names(W042_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W042_G5_Dataset[,2:3] = apply(W042_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W042B,W042Atr,W042_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W043                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W043B <- read.csv('./Fibre count Summary/W043_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W043Atr <- read.csv('./Fibre count Summary/W043_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W043B$Slice<- gsub("_B.TIF","",W043B$Slice)

# Create table
W043_G5_Dataset_pending <- data.frame(rbind(W043B$Slice, W043B$Count, W043Atr$Count))
W043_G5_Dataset<-as.data.frame(t(W043_G5_Dataset_pending))
names(W043_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W043_G5_Dataset[,2:3] = apply(W043_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W043B,W043Atr,W043_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W044                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W044B <- read.csv('./Fibre count Summary/W044_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W044Atr <- read.csv('./Fibre count Summary/W044_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W044B$Slice<- gsub("_B.TIF","",W044B$Slice)

# Create table
W044_G5_Dataset_pending <- data.frame(rbind(W044B$Slice, W044B$Count, W044Atr$Count))
W044_G5_Dataset<-as.data.frame(t(W044_G5_Dataset_pending))
names(W044_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W044_G5_Dataset[,2:3] = apply(W044_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W044B,W044Atr,W044_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W045                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W045B <- read.csv('./Fibre count Summary/W045_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W045Atr <- read.csv('./Fibre count Summary/W045_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W045B$Slice<- gsub("_B.TIF","",W045B$Slice)

# Create table
W045_G5_Dataset_pending <- data.frame(rbind(W045B$Slice, W045B$Count, W045Atr$Count))
W045_G5_Dataset<-as.data.frame(t(W045_G5_Dataset_pending))
names(W045_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W045_G5_Dataset[,2:3] = apply(W045_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W045B,W045Atr,W045_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W046                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W046B <- read.csv('./Fibre count Summary/W046_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W046Atr <- read.csv('./Fibre count Summary/W046_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W046B$Slice<- gsub("_B.TIF","",W046B$Slice)

# Create table
W046_G5_Dataset_pending <- data.frame(rbind(W046B$Slice, W046B$Count, W046Atr$Count))
W046_G5_Dataset<-as.data.frame(t(W046_G5_Dataset_pending))
names(W046_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W046_G5_Dataset[,2:3] = apply(W046_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W046B,W046Atr,W046_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W047                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W047B <- read.csv('./Fibre count Summary/W047_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W047Atr <- read.csv('./Fibre count Summary/W047_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W047B$Slice<- gsub("_B.TIF","",W047B$Slice)

# Create table
W047_G5_Dataset_pending <- data.frame(rbind(W047B$Slice, W047B$Count, W047Atr$Count))
W047_G5_Dataset<-as.data.frame(t(W047_G5_Dataset_pending))
names(W047_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W047_G5_Dataset[,2:3] = apply(W047_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W047B,W047Atr,W047_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W048                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W048B <- read.csv('./Fibre count Summary/W048_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W048Atr <- read.csv('./Fibre count Summary/W048_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W048B$Slice<- gsub("_B.TIF","",W048B$Slice)

# Create table
W048_G5_Dataset_pending <- data.frame(rbind(W048B$Slice, W048B$Count, W048Atr$Count))
W048_G5_Dataset<-as.data.frame(t(W048_G5_Dataset_pending))
names(W048_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W048_G5_Dataset[,2:3] = apply(W048_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W048B,W048Atr,W048_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W049                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W049B <- read.csv('./Fibre count Summary/W049_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W049Atr <- read.csv('./Fibre count Summary/W049_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W049B$Slice<- gsub("_B.TIF","",W049B$Slice)

# Create table
W049_G5_Dataset_pending <- data.frame(rbind(W049B$Slice, W049B$Count, W049Atr$Count))
W049_G5_Dataset<-as.data.frame(t(W049_G5_Dataset_pending))
names(W049_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W049_G5_Dataset[,2:3] = apply(W049_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W049B,W049Atr,W049_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W050                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W050B <- read.csv('./Fibre count Summary/W050_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W050Atr <- read.csv('./Fibre count Summary/W050_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W050B$Slice<- gsub("_B.TIF","",W050B$Slice)

# Create table
W050_G5_Dataset_pending <- data.frame(rbind(W050B$Slice, W050B$Count, W050Atr$Count))
W050_G5_Dataset<-as.data.frame(t(W050_G5_Dataset_pending))
names(W050_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W050_G5_Dataset[,2:3] = apply(W050_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W050B,W050Atr,W050_G5_Dataset_pending)

#-----------------------------------------------------------#
#                             W051                          #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W051B <- read.csv('./Fibre count Summary/W051_B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W051Atr <- read.csv('./Fibre count Summary/W051_Atr_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
W051B$Slice<- gsub("_B.TIF","",W051B$Slice)

# Create table
W051_G5_Dataset_pending <- data.frame(rbind(W051B$Slice, W051B$Count, W051Atr$Count))
W051_G5_Dataset<-as.data.frame(t(W051_G5_Dataset_pending))
names(W051_G5_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W051_G5_Dataset[,2:3] = apply(W051_G5_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W051B,W051Atr,W051_G5_Dataset_pending)

#####################################################
#             12 GARMENTS - NO DETERGENT            #
#####################################################
#-----------------------------------------------------------#
#                         W000_G12A                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G12A <- read.csv('./Fibre count Summary/W000_G12A_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G12AB <- W000_G12A %>% filter(grepl('_B.', Slice))
W000_G12AAtr <- W000_G12A %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G12AB and W000_G12AAtr
W000_G12AB$Slice<- gsub(".TIF","",W000_G12AB$Slice)
W000_G12AAtr$Slice<- gsub(".TIF","",W000_G12AAtr$Slice)

# Create table
W000_G12A_Dataset_pending <- data.frame(rbind(W000_G12AB$Slice, W000_G12AB$Count, W000_G12AAtr$Count))
W000_G12A_Dataset<-as.data.frame(t(W000_G12A_Dataset_pending))
names(W000_G12A_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G12A_Dataset[,2:3] = apply(W000_G12A_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G12A,W000_G12AB,W000_G12AAtr,W000_G12A_Dataset_pending)

#-----------------------------------------------------------#
#                         W000_G12B                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G12B <- read.csv('./Fibre count Summary/W000_G12B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G12BB <- W000_G12B %>% filter(grepl('_B.', Slice))
W000_G12BAtr <- W000_G12B %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G12BB and W000_G12BAtr
W000_G12BB$Slice<- gsub(".TIF","",W000_G12BB$Slice)
W000_G12BAtr$Slice<- gsub(".TIF","",W000_G12BAtr$Slice)

# Create table
W000_G12B_Dataset_pending <- data.frame(rbind(W000_G12BB$Slice, W000_G12BB$Count, W000_G12BAtr$Count))
W000_G12B_Dataset<-as.data.frame(t(W000_G12B_Dataset_pending))
names(W000_G12B_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G12B_Dataset[,2:3] = apply(W000_G12B_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G12B,W000_G12BB,W000_G12BAtr,W000_G12B_Dataset_pending)

#-----------------------------------------------------------#
#                         W000_G12C                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W000_G12C <- read.csv('./Fibre count Summary/W000_G12C_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W000_G12CB <- W000_G12C %>% filter(grepl('_B.', Slice))
W000_G12CAtr <- W000_G12C %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W000_G12CB and W000_G12CAtr
W000_G12CB$Slice<- gsub(".TIF","",W000_G12CB$Slice)
W000_G12CAtr$Slice<- gsub(".TIF","",W000_G12CAtr$Slice)

# Create table
W000_G12C_Dataset_pending <- data.frame(rbind(W000_G12CB$Slice, W000_G12CB$Count, W000_G12CAtr$Count))
W000_G12C_Dataset<-as.data.frame(t(W000_G12C_Dataset_pending))
names(W000_G12C_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W000_G12C_Dataset[,2:3] = apply(W000_G12C_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W000_G12C,W000_G12CB,W000_G12CAtr,W000_G12C_Dataset_pending)

#-----------------------------------------------------------#
#                         W001_G12A                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001_G12A <- read.csv('./Fibre count Summary/W001_G12A_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001_G12AB <- W001_G12A %>% filter(grepl('_B.', Slice))
W001_G12AAtr <- W001_G12A %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001_G12AB and W001_G12AAtr
W001_G12AB$Slice<- gsub(".TIF","",W001_G12AB$Slice)
W001_G12AAtr$Slice<- gsub(".TIF","",W001_G12AAtr$Slice)

# Create table
W001_G12A_Dataset_pending <- data.frame(rbind(W001_G12AB$Slice, W001_G12AB$Count, W001_G12AAtr$Count))
W001_G12A_Dataset<-as.data.frame(t(W001_G12A_Dataset_pending))
names(W001_G12A_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G12A_Dataset[,2:3] = apply(W001_G12A_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001_G12A,W001_G12AB,W001_G12AAtr,W001_G12A_Dataset_pending)

#-----------------------------------------------------------#
#                         W001_G12B                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001_G12B <- read.csv('./Fibre count Summary/W001_G12B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001_G12BB <- W001_G12B %>% filter(grepl('_B.', Slice))
W001_G12BAtr <- W001_G12B %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001_G12BB and W001_G12BAtr
W001_G12BB$Slice<- gsub(".TIF","",W001_G12BB$Slice)
W001_G12BAtr$Slice<- gsub(".TIF","",W001_G12BAtr$Slice)

# Create table
W001_G12B_Dataset_pending <- data.frame(rbind(W001_G12BB$Slice, W001_G12BB$Count, W001_G12BAtr$Count))
W001_G12B_Dataset<-as.data.frame(t(W001_G12B_Dataset_pending))
names(W001_G12B_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G12B_Dataset[,2:3] = apply(W001_G12B_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001_G12B,W001_G12BB,W001_G12BAtr,W001_G12B_Dataset_pending)

#-----------------------------------------------------------#
#                         W001_G12C                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W001_G12C <- read.csv('./Fibre count Summary/W001_G12C_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W001_G12CB <- W001_G12C %>% filter(grepl('_B.', Slice))
W001_G12CAtr <- W001_G12C %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W001_G12CB and W001_G12CAtr
W001_G12CB$Slice<- gsub(".TIF","",W001_G12CB$Slice)
W001_G12CAtr$Slice<- gsub(".TIF","",W001_G12CAtr$Slice)

# Create table
W001_G12C_Dataset_pending <- data.frame(rbind(W001_G12CB$Slice, W001_G12CB$Count, W001_G12CAtr$Count))
W001_G12C_Dataset<-as.data.frame(t(W001_G12C_Dataset_pending))
names(W001_G12C_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W001_G12C_Dataset[,2:3] = apply(W001_G12C_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W001_G12C,W001_G12CB,W001_G12CAtr,W001_G12C_Dataset_pending)

#-----------------------------------------------------------#
#                         W002_G12A                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002_G12A <- read.csv('./Fibre count Summary/W002_G12A_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002_G12AB <- W002_G12A %>% filter(grepl('_B.', Slice))
W002_G12AAtr <- W002_G12A %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002_G12AB and W002_G12AAtr
W002_G12AB$Slice<- gsub(".TIF","",W002_G12AB$Slice)
W002_G12AAtr$Slice<- gsub(".TIF","",W002_G12AAtr$Slice)

# Create table
W002_G12A_Dataset_pending <- data.frame(rbind(W002_G12AB$Slice, W002_G12AB$Count, W002_G12AAtr$Count))
W002_G12A_Dataset<-as.data.frame(t(W002_G12A_Dataset_pending))
names(W002_G12A_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G12A_Dataset[,2:3] = apply(W002_G12A_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002_G12A,W002_G12AB,W002_G12AAtr,W002_G12A_Dataset_pending)

#-----------------------------------------------------------#
#                         W002_G12B                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002_G12B <- read.csv('./Fibre count Summary/W002_G12B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002_G12BB <- W002_G12B %>% filter(grepl('_B.', Slice))
W002_G12BAtr <- W002_G12B %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002_G12BB and W002_G12BAtr
W002_G12BB$Slice<- gsub(".TIF","",W002_G12BB$Slice)
W002_G12BAtr$Slice<- gsub(".TIF","",W002_G12BAtr$Slice)

# Create table
W002_G12B_Dataset_pending <- data.frame(rbind(W002_G12BB$Slice, W002_G12BB$Count, W002_G12BAtr$Count))
W002_G12B_Dataset<-as.data.frame(t(W002_G12B_Dataset_pending))
names(W002_G12B_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G12B_Dataset[,2:3] = apply(W002_G12B_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002_G12B,W002_G12BB,W002_G12BAtr,W002_G12B_Dataset_pending)

#-----------------------------------------------------------#
#                         W002_G12C                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W002_G12C <- read.csv('./Fibre count Summary/W002_G12C_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W002_G12CB <- W002_G12C %>% filter(grepl('_B.', Slice))
W002_G12CAtr <- W002_G12C %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W002_G12CB and W002_G12CAtr
W002_G12CB$Slice<- gsub(".TIF","",W002_G12CB$Slice)
W002_G12CAtr$Slice<- gsub(".TIF","",W002_G12CAtr$Slice)

# Create table
W002_G12C_Dataset_pending <- data.frame(rbind(W002_G12CB$Slice, W002_G12CB$Count, W002_G12CAtr$Count))
W002_G12C_Dataset<-as.data.frame(t(W002_G12C_Dataset_pending))
names(W002_G12C_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W002_G12C_Dataset[,2:3] = apply(W002_G12C_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W002_G12C,W002_G12CB,W002_G12CAtr,W002_G12C_Dataset_pending)

#-----------------------------------------------------------#
#                         W003_G12A                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003_G12A <- read.csv('./Fibre count Summary/W003_G12A_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003_G12AB <- W003_G12A %>% filter(grepl('_B.', Slice))
W003_G12AAtr <- W003_G12A %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003_G12AB and W003_G12AAtr
W003_G12AB$Slice<- gsub(".TIF","",W003_G12AB$Slice)
W003_G12AAtr$Slice<- gsub(".TIF","",W003_G12AAtr$Slice)

# Create table
W003_G12A_Dataset_pending <- data.frame(rbind(W003_G12AB$Slice, W003_G12AB$Count, W003_G12AAtr$Count))
W003_G12A_Dataset<-as.data.frame(t(W003_G12A_Dataset_pending))
names(W003_G12A_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G12A_Dataset[,2:3] = apply(W003_G12A_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003_G12A,W003_G12AB,W003_G12AAtr,W003_G12A_Dataset_pending)

#-----------------------------------------------------------#
#                         W003_G12B                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003_G12B <- read.csv('./Fibre count Summary/W003_G12B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003_G12BB <- W003_G12B %>% filter(grepl('_B.', Slice))
W003_G12BAtr <- W003_G12B %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003_G12BB and W003_G12BAtr
W003_G12BB$Slice<- gsub(".TIF","",W003_G12BB$Slice)
W003_G12BAtr$Slice<- gsub(".TIF","",W003_G12BAtr$Slice)

# Create table
W003_G12B_Dataset_pending <- data.frame(rbind(W003_G12BB$Slice, W003_G12BB$Count, W003_G12BAtr$Count))
W003_G12B_Dataset<-as.data.frame(t(W003_G12B_Dataset_pending))
names(W003_G12B_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G12B_Dataset[,2:3] = apply(W003_G12B_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003_G12B,W003_G12BB,W003_G12BAtr,W003_G12B_Dataset_pending)

#-----------------------------------------------------------#
#                         W003_G12C                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W003_G12C <- read.csv('./Fibre count Summary/W003_G12C_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W003_G12CB <- W003_G12C %>% filter(grepl('_B.', Slice))
W003_G12CAtr <- W003_G12C %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W003_G12CB and W003_G12CAtr
W003_G12CB$Slice<- gsub(".TIF","",W003_G12CB$Slice)
W003_G12CAtr$Slice<- gsub(".TIF","",W003_G12CAtr$Slice)

# Create table
W003_G12C_Dataset_pending <- data.frame(rbind(W003_G12CB$Slice, W003_G12CB$Count, W003_G12CAtr$Count))
W003_G12C_Dataset<-as.data.frame(t(W003_G12C_Dataset_pending))
names(W003_G12C_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W003_G12C_Dataset[,2:3] = apply(W003_G12C_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W003_G12C,W003_G12CB,W003_G12CAtr,W003_G12C_Dataset_pending)

#-----------------------------------------------------------#
#                         W004_G12A                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004_G12A <- read.csv('./Fibre count Summary/W004_G12A_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004_G12AB <- W004_G12A %>% filter(grepl('_B.', Slice))
W004_G12AAtr <- W004_G12A %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004_G12AB and W004_G12AAtr
W004_G12AB$Slice<- gsub(".TIF","",W004_G12AB$Slice)
W004_G12AAtr$Slice<- gsub(".TIF","",W004_G12AAtr$Slice)

# Create table
W004_G12A_Dataset_pending <- data.frame(rbind(W004_G12AB$Slice, W004_G12AB$Count, W004_G12AAtr$Count))
W004_G12A_Dataset<-as.data.frame(t(W004_G12A_Dataset_pending))
names(W004_G12A_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G12A_Dataset[,2:3] = apply(W004_G12A_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004_G12A,W004_G12AB,W004_G12AAtr,W004_G12A_Dataset_pending)

#-----------------------------------------------------------#
#                         W004_G12B                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004_G12B <- read.csv('./Fibre count Summary/W004_G12B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004_G12BB <- W004_G12B %>% filter(grepl('_B.', Slice))
W004_G12BAtr <- W004_G12B %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004_G12BB and W004_G12BAtr
W004_G12BB$Slice<- gsub(".TIF","",W004_G12BB$Slice)
W004_G12BAtr$Slice<- gsub(".TIF","",W004_G12BAtr$Slice)

# Create table
W004_G12B_Dataset_pending <- data.frame(rbind(W004_G12BB$Slice, W004_G12BB$Count, W004_G12BAtr$Count))
W004_G12B_Dataset<-as.data.frame(t(W004_G12B_Dataset_pending))
names(W004_G12B_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G12B_Dataset[,2:3] = apply(W004_G12B_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004_G12B,W004_G12BB,W004_G12BAtr,W004_G12B_Dataset_pending)

#-----------------------------------------------------------#
#                         W004_G12C                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W004_G12C <- read.csv('./Fibre count Summary/W004_G12C_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W004_G12CB <- W004_G12C %>% filter(grepl('_B.', Slice))
W004_G12CAtr <- W004_G12C %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W004_G12CB and W004_G12CAtr
W004_G12CB$Slice<- gsub(".TIF","",W004_G12CB$Slice)
W004_G12CAtr$Slice<- gsub(".TIF","",W004_G12CAtr$Slice)

# Create table
W004_G12C_Dataset_pending <- data.frame(rbind(W004_G12CB$Slice, W004_G12CB$Count, W004_G12CAtr$Count))
W004_G12C_Dataset<-as.data.frame(t(W004_G12C_Dataset_pending))
names(W004_G12C_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W004_G12C_Dataset[,2:3] = apply(W004_G12C_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W004_G12C,W004_G12CB,W004_G12CAtr,W004_G12C_Dataset_pending)

#-----------------------------------------------------------#
#                         W005_G12A                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005_G12A <- read.csv('./Fibre count Summary/W005_G12A_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005_G12AB <- W005_G12A %>% filter(grepl('_B.', Slice))
W005_G12AAtr <- W005_G12A %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005_G12AB and W005_G12AAtr
W005_G12AB$Slice<- gsub(".TIF","",W005_G12AB$Slice)
W005_G12AAtr$Slice<- gsub(".TIF","",W005_G12AAtr$Slice)

# Create table
W005_G12A_Dataset_pending <- data.frame(rbind(W005_G12AB$Slice, W005_G12AB$Count, W005_G12AAtr$Count))
W005_G12A_Dataset<-as.data.frame(t(W005_G12A_Dataset_pending))
names(W005_G12A_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G12A_Dataset[,2:3] = apply(W005_G12A_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005_G12A,W005_G12AB,W005_G12AAtr,W005_G12A_Dataset_pending)

#-----------------------------------------------------------#
#                         W005_G12B                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005_G12B <- read.csv('./Fibre count Summary/W005_G12B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005_G12BB <- W005_G12B %>% filter(grepl('_B.', Slice))
W005_G12BAtr <- W005_G12B %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005_G12BB and W005_G12BAtr
W005_G12BB$Slice<- gsub(".TIF","",W005_G12BB$Slice)
W005_G12BAtr$Slice<- gsub(".TIF","",W005_G12BAtr$Slice)

# Create table
W005_G12B_Dataset_pending <- data.frame(rbind(W005_G12BB$Slice, W005_G12BB$Count, W005_G12BAtr$Count))
W005_G12B_Dataset<-as.data.frame(t(W005_G12B_Dataset_pending))
names(W005_G12B_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G12B_Dataset[,2:3] = apply(W005_G12B_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005_G12B,W005_G12BB,W005_G12BAtr,W005_G12B_Dataset_pending)

#-----------------------------------------------------------#
#                         W005_G12C                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W005_G12C <- read.csv('./Fibre count Summary/W005_G12C_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W005_G12CB <- W005_G12C %>% filter(grepl('_B.', Slice))
W005_G12CAtr <- W005_G12C %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W005_G12CB and W005_G12CAtr
W005_G12CB$Slice<- gsub(".TIF","",W005_G12CB$Slice)
W005_G12CAtr$Slice<- gsub(".TIF","",W005_G12CAtr$Slice)

# Create table
W005_G12C_Dataset_pending <- data.frame(rbind(W005_G12CB$Slice, W005_G12CB$Count, W005_G12CAtr$Count))
W005_G12C_Dataset<-as.data.frame(t(W005_G12C_Dataset_pending))
names(W005_G12C_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W005_G12C_Dataset[,2:3] = apply(W005_G12C_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W005_G12C,W005_G12CB,W005_G12CAtr,W005_G12C_Dataset_pending)

#-----------------------------------------------------------#
#                         W006_G12A                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006_G12A <- read.csv('./Fibre count Summary/W006_G12A_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W006_G12AB <- W006_G12A %>% filter(grepl('_B.', Slice))
W006_G12AAtr <- W006_G12A %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W006_G12AB and W006_G12AAtr
W006_G12AB$Slice<- gsub(".TIF","",W006_G12AB$Slice)
W006_G12AAtr$Slice<- gsub(".TIF","",W006_G12AAtr$Slice)

# Create table
W006_G12A_Dataset_pending <- data.frame(rbind(W006_G12AB$Slice, W006_G12AB$Count, W006_G12AAtr$Count))
W006_G12A_Dataset<-as.data.frame(t(W006_G12A_Dataset_pending))
names(W006_G12A_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G12A_Dataset[,2:3] = apply(W006_G12A_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006_G12A,W006_G12AB,W006_G12AAtr,W006_G12A_Dataset_pending)

#-----------------------------------------------------------#
#                         W006_G12B                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006_G12B <- read.csv('./Fibre count Summary/W006_G12B_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W006_G12BB <- W006_G12B %>% filter(grepl('_B.', Slice))
W006_G12BAtr <- W006_G12B %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W006_G12BB and W006_G12BAtr
W006_G12BB$Slice<- gsub(".TIF","",W006_G12BB$Slice)
W006_G12BAtr$Slice<- gsub(".TIF","",W006_G12BAtr$Slice)

# Create table
W006_G12B_Dataset_pending <- data.frame(rbind(W006_G12BB$Slice, W006_G12BB$Count, W006_G12BAtr$Count))
W006_G12B_Dataset<-as.data.frame(t(W006_G12B_Dataset_pending))
names(W006_G12B_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G12B_Dataset[,2:3] = apply(W006_G12B_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006_G12B,W006_G12BB,W006_G12BAtr,W006_G12B_Dataset_pending)

#-----------------------------------------------------------#
#                         W006_G12C                           #
#-----------------------------------------------------------#
###_________________Data loading_________________###
W006_G12C <- read.csv('./Fibre count Summary/W006_G12C_Summary.csv', sep="," ,header = T,fileEncoding = 'UTF-8-BOM')
# Creating the different dataframe before and after transfer
W006_G12CB <- W006_G12C %>% filter(grepl('_B.', Slice))
W006_G12CAtr <- W006_G12C %>% filter(grepl('_Atr.TIF', Slice))

# removing the ".TIF" in W006_G12CB and W006_G12CAtr
W006_G12CB$Slice<- gsub(".TIF","",W006_G12CB$Slice)
W006_G12CAtr$Slice<- gsub(".TIF","",W006_G12CAtr$Slice)

# Create table
W006_G12C_Dataset_pending <- data.frame(rbind(W006_G12CB$Slice, W006_G12CB$Count, W006_G12CAtr$Count))
W006_G12C_Dataset<-as.data.frame(t(W006_G12C_Dataset_pending))
names(W006_G12C_Dataset) <- c("Sample", "Before transfer", "After transfer")

# change factor to numeric in the column 2 to 3
W006_G12C_Dataset[,2:3] = apply(W006_G12C_Dataset[,2:3], 2, function(x) as.numeric(as.character(x)));

# remove unused dataframe
rm(W006_G12C,W006_G12CB,W006_G12CAtr,W006_G12C_Dataset_pending)

W000_G12_Dataset <- rbind()